spring.application.name=meuape
spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=admin
spring.data.mongodb.password=PortCC@192911
spring.data.mongodb.database=meuape
api.prefix=api/v1

jwt.header=Authorization
security.jwt.token.secret-key=VGhpcyBpcyBhIHNlY3VyZSBrZXkgZm9yIEpXVCAyNTYgYml0ca==
security.jwt.token.expire-length=86400000

api.security.token.secret=d6bf5880-82d7-4305-a94c-36ab184b9c63

server.error.include-message=always
server.error.include-stacktrace=on_param

