spring.application.name=meuape

spring.data.mongodb.uri=mongodb://admin:PortCC%40192911@127.0.0.1:27017/meuape?authSource=admin&authMechanism=SCRAM-SHA-256

#spring.data.mongodb.authentication-database=${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}
#spring.data.mongodb.username=${SPRING_DATA_MONGODB_USERNAME:admin}
#spring.data.mongodb.password=${SPRING_DATA_MONGODB_PASSWORD:PortCC@192911}
#spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:meuape}
#spring.data.mongodb.host=${SPRING_DATA_MONGODB_HOST:localhost}

jwt.header=Authorization
security.jwt.token.secret-key=VGhpcyBpcyBhIHNlY3VyZSBrZXkgZm9yIEpXVCAyNTYgYml0ca==
security.jwt.token.expire-length=3600000
security.jwt.token.refresh.expire-length=604800000
api.security.token.secret=d6bf5880-82d7-4305-a94c-36ab184b9c63

server.error.include-message=always
server.error.include-stacktrace=on_param

spring.threads.virtual.enabled=true